config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :contacts, only: [:create, :show]
  resources :plans_selecteds
  resources :plans
  
  mount Resque::Server.new, :at => "/resque"

  resources :favorite_lands, only: [:index, :create, :destroy]
  resources :favorite_houses, only: [:index, :create, :destroy]
  resources :profile_lands, only: [:index]
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :lands do 
    get 'show_images'
   
    collection do 
      get 'search'
    end
  end
  
  resources :houses do
    get 'show_images' 
    
    collection do
      get 'search'
      get 'search_advanced'
      get 'rent'
      get 'buy'
    end
  
  end

  root "home#index"

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :profile_lands
  has_many :lands, through: :profile_lands, dependent: :destroy
  has_many :favorite_land, dependent: :destroy

  has_many :profile_houses
  has_many :houses, through: :profile_houses, dependent: :destroy
  has_many :favorite_house, dependent: :destroy

  validates_presence_of :name_profile, :profile_type, :gender
  validates :phone1, :phone2, presence: true, uniqueness: true

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [140, 140]
  end
  
  enum gender: { masculine: "MASCULINE", feminine: "FEMININE" }
  enum profile_type: {
    super_adminstrador: "SUPER_ADMINISTRADOR756", 
    empresa: "EMPRESA", 
    cliente: "CLIENTE"
  }
  
  def self.find_by_user(user) 
    Profile.find_by(user_id: user.id)
  end

  def self.find_by_house(house)
    Profile.joins(:profile_houses)
           .where("profile_houses.house_id = #{house.id}")
           .take
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_profile_by_user_id, only: [ :new, :update ]

  include ProfilesConcerns

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.includes(:user, :address)
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new

   if !@profile.nil?
      respond_to do |format| 
        format.html { redirect_to profile_url(@profile) }
        format.json { render :show, status: :created, location: @profile}
      end
   else
      @profile = Profile.new
      @profile.build_address
   end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    
    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
         
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    

    respond_to do |format|
      format.html { redirect_to profiles_url(locale: I18n.locale), notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end
    
    def set_profile_by_user_id 
      @profile ||= Profile.find_by_user_id(current_user.id)
      @profile
    end
    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(
        :name_profile, 
        :phone1, 
        :phone2, 
        :profile_type, 
        :gender,
        :image,
        address_attributes: [:id, :street, :city_id, :_destroy] 
      )
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
 <div class="container col-lg-6 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
        <div class="card-title">
            <div class="d-flex justify-content-center">

              <%= render "image", image_profile: profile.image %>
              
            </div>
            <h4 class="text-center text-pink">Editar Perfil</h4>
        </div>
        <div class="row my-2">
          <%= bootstrap_form_with(model: profile) do |form| %>
            <% if profile.errors.any? %>
              <div style="color: red">
                <h5><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h5>

                <ul>
                  <% profile.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div>
              <%= form.text_field :name_profile, 
              label: Profile.human_attribute_name(:name_profile), class: 'text-light-emphasis' %>
              <%= form.file_field :image, label: Profile.human_attribute_name(:image),
               class: 'text-light-emphasis'%>  
              <%= form.select :gender, Profile.genders, {label: :gender}, class: 'text-light-emphasis'%>

              <%= form.select :profile_type, Profile.profile_types, 
                {label: Profile.human_attribute_name(:profile_type)}, class: 'text-light-emphasis' %>
              <%= form.telephone_field :phone1, label: Profile.human_attribute_name(:phone1), 
              class: 'text-light-emphasis' %>
              <%= form.telephone_field :phone2, label: Profile.human_attribute_name(:phone2), 
              class: 'text-light-emphasis' %>
            
              <%= form.collection_select :province_id, Province.order(:province_name), :id, :province_name, 
              { label: Province.model_name.human(count: 1) }, 
              {class:"province province_select text-light-emphasis"} %> 
                
              <%= form.fields_for :address do |address_form| %>
                <%= address_form.collection_select :city_id, cities_array_empty, :id, :city_name, 
                { label: City.model_name.human(count: 1)},  {class:"city_select text-light-emphasis"}%>
                <%= address_form.text_field :street, label: Address.human_attribute_name(:street), 
                class: 'text-light-emphasis' %>
              <% end %> 
              
      
            </div>

            <div class="mb-3 d-grid gap-2">
              <%= form.submit class: "btn btn-info" %>
            </div>
          <% end %>

        </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

app/views/profiles/_image.erb
<% if !image_profile.attached? %>

    <svg class="bd-placeholder-img rounded-circle" width="140" height="140" 
        role="img" aria-label="Placeholder: 140x140" 
        preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Upload an imagem</title>
        <rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" 
        fill="#777" dy=".3em">140x140</text>
    </svg>
<% else %>

    <%= image_tag(image_profile, width:"140", height:"140", role:"img", class: "rounded-circle" ) %>
    
<% end %>

app/views/profiles/_image.html.erb
<% if !image_profile.attached? %>

    <svg class="bd-placeholder-img rounded-circle" width="140" height="140" 
        role="img" aria-label="Placeholder: 140x140" 
        preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Upload an imagem</title>
        <rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" 
        fill="#777" dy=".3em">140x140</text>
    </svg>
<% else %>

    <%= image_tag(image_profile, width:"140", height:"140", role:"img", class: "rounded-circle" ) %>
    
<% end %>

app/views/profiles/_profile.html.erb
<div class="container col-lg-6 my-4" id="<%= dom_id profile %>" >
  <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <div class="card-title text-center">
                 <%= render "image", image_profile: profile.image %>
              </div>
              <h4 class="text-center text-pink"><%= profile.name_profile %></h4>
          </div>
          <div class="text-center my-2 text-primary-emphasis">
              
              <strong> <%= Profile.human_attribute_name(:gender) %>:</strong> <%= profile.gender %> <br>
              <strong>Email:</strong>  <%= profile.user.email %> <br>
              <strong><%= Profile.human_attribute_name(:profile_type) %>:</strong> <%= remove_underscore( profile.profile_type )  %> <br>
              <strong><%= Address.model_name.human(count: 1) %>: </strong> 
                <%= profile.address.street %>, 
                <%= profile.address.city.city_name %>,  
                <%= profile.address.city.province.province_name %>
                <br>
              <strong><%= t(:telephones) %>: </strong> <%= profile.phone1 %>, <%= profile.phone2 %>
  
          </div>
          <div class="mb-3 d-grid gap-2">
              <%= link_to t("links.edit"), edit_profile_path(profile), class: "btn btn-info" %> 
          </div>
        </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<%= render "form", profile: @profile %>

app/views/profiles/index.html.erb
<h5>Profiles</h5>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<%= render @profile %>