config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :contacts, only: [:create, :show]
  resources :plans_selecteds
  resources :plans
  
  mount Resque::Server.new, :at => "/resque"

  resources :favorite_lands, only: [:index, :create, :destroy]
  resources :favorite_houses, only: [:index, :create, :destroy]
  resources :profile_lands, only: [:index]
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :lands do 
    get 'show_images'
   
    collection do 
      get 'search'
    end
  end
  
  resources :houses do
    get 'show_images' 
    
    collection do
      get 'search'
      get 'search_advanced'
      get 'rent'
      get 'buy'
    end
  
  end

  root "home#index"

end

app/models/plans_selected.rb
class PlansSelected < ApplicationRecord
  belongs_to :plan
  belongs_to :user

  enum duration: { monthly: 30, quarterly: 90, semiannual: 180,  annual: 360 }

  validates :user, uniqueness: {  message: "User can have only one plan selected." }


  scope :find_by_user, ->(user) { where(user_id: user.id) }

  def self.find_plan_selected_by_user(user) 
    PlansSelected.joins(:plan)
                 .joins(:user)
                 .where("plans_selecteds.day_used < plans_selecteds.duration and plans_selecteds.user_id = #{user.id}").take
  end

       
end

app/controllers/plans_selecteds_controller.rb
class PlansSelectedsController < ApplicationController
  before_action :set_plans_selected, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_plan_selected

  # GET /plans_selecteds or /plans_selecteds.json
  def index
    if current_user.profile.super_adminstrador?
      @plans_selecteds = PlansSelected.includes(:plan)
    else
      @plans_selected = PlansSelected.find_by_user(current_user).first
      
      if @plans_selected
        redirect_to plans_selected_url(@plans_selected)
      else
        redirect_to plans_url(locale: I18n.locale)
      end
    end
  end

  # GET /plans_selecteds/1 or /plans_selecteds/1.json
  def show
  end

  # GET /plans_selecteds/new
  def new
    @plans_selected = PlansSelected.new
    redirect_to plans_url(locale: I18n.locale)
  end

  # GET /plans_selecteds/1/edit
  def edit
  end

  # POST /plans_selecteds or /plans_selecteds.json
  def create
    @plans_selected = PlansSelected.new(plans_selected_params)
    @plans_selected.user_id = current_user.id
    plan_selected = PlansSelected.find_by_user(current_user).take
  
    if plan_selected
      @plans_selected = plan_selected
      redirect_to @plans_selected and return
    end

    respond_to do |format|
      if @plans_selected.save
        format.html { redirect_to plans_selected_url(@plans_selected), notice: "Plans selected was successfully created." }
        format.json { render :show, status: :created, location: @plans_selected }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plans_selected.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /plans_selecteds/1/select


  # PATCH/PUT /plans_selecteds/1 or /plans_selecteds/1.json
  def update
    
    respond_to do |format|
      debugger
      if @plans_selected.update(plans_selected_params)
        format.html { redirect_to plans_selected_url(@plans_selected), notice: "Plans selected was successfully updated." }
        format.json { render :show, status: :ok, location: @plans_selected }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plans_selected.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans_selecteds/1 or /plans_selecteds/1.json
  def destroy
    plan_selected = PlansSelected.find_plan_selected_by_user(current_user)

    respond_to do |format|
      if plan_selected.activated 
        format.html { redirect_to plans_selected_url(plan_selected), info: "This Plan is activated. You can not delete." }
      else  
        @plans_selected.destroy
        format.html { redirect_to plans_selecteds_url(locale: I18n.locale), notice: "Plans selected was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
  
  def invalid_plan_selected
    logger.error "Attemped to access invalid Plan #{params[:id]}"
    redirect_to houses_url(locale: I18n.locale), info: "Invalid Plan."
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_plans_selected
      @plans_selected = PlansSelected.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plans_selected_params
      params.require(:plans_selected).permit(
        :day_used, 
        :duration, 
        :first_time, 
        :activated, 
        :plan_id
      )
    end

end

app/helpers/plans_selecteds_helper.rb
module PlansSelectedsHelper
end

app/views/plans_selecteds/_form.html.erb
<div class="container col-lg-6 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">

        <%= bootstrap_form_with(model: plans_selected) do |form| %>
          <% if plans_selected.errors.any? %>
            <div style="color: red">
              <h5><%= pluralize(plans_selected.errors.count, "error") %> prohibited this plans_selected from being saved:</h5>

              <ul>
                <% plans_selected.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

            <%= form.number_field :day_used, class: 'text-light-emphasis' %>
            <%= form.collection_select :plan_id, Plan.order(:name_plans), :id, 
                :name_plans, { label: "Plans" }, class: 'text-light-emphasis'  %> 
            <%= form.select :duration, PlansSelected.durations.keys, class: 'text-light-emphasis' %>
             
            <%= form.check_box :activated, class: 'text-light-emphasis' %>
            <%= form.check_box :first_time, class: 'text-light-emphasis' %>
           <div class="mb-3 d-grid gap-2">
            <%= form.submit class:"btn btn-info" %>
            
            <%= link_to "Back to plans selecteds", plans_selecteds_path, class: "link-primary"%>
          </div>
        <% end %>
        </div>
    </div>
</div>

app/views/plans_selecteds/_plans_selected.html.erb
  <div class="col" id="<%= dom_id plans_selected %>">

    <th scope="row"> <%= plans_selected.id %></th>
      <td><%= plans_selected.user.profile.name_profile %></td>
      <td><%= plans_selected.user.email %></td>
      <td><%= plans_selected.plan.name_plans%></td>
      <td><%= plans_selected.duration %></td>
      <td><%= plans_selected.plan.price %></td>
      <td><%= plans_selected.day_used %></td>

      <% if plans_selected.activated  %>
        <td class="text-success"><%= plans_selected.activated %></td>
      <% else %>
        <td class="text-danger"><%= plans_selected.activated %></td>
      <% end %>
      

      <% if plans_selected.first_time  %>
        <td class="text-success"><%= plans_selected.first_time %></td>
      <% else %>
        <td class="text-danger"><%= plans_selected.first_time %></td>
      <% end %>
      <td><%= button_to "Destroy", plans_selected, method: :delete, 
       data: { confirm: "Está ação irá eliminar este plano selecionado. Deseja continuar?", 
             turbo_confirm: "Está ação irá eliminar este plano selecionado. Deseja continuar?" }, 
             class:"btn btn-danger"%></td>

      <% if current_user.profile.super_adminstrador? %>
        <td><%= link_to "Edit", edit_plans_selected_path(plans_selected), class:"btn btn-info"%></td>
        
        <% if !plans_selected.activated %>
          <td>
            <%= bootstrap_form_with(model: plans_selected) do |form| %>
              <% if plans_selected.errors.any? %>
                <div style="color: red">
                  <h2><%= pluralize(plans_selected.errors.count, "error") %> prohibited this plans_selected from being saved:</h2>

                  <ul>
                    <% plans_selected.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
                <%= form.hidden_field :duration, value: plans_selected.duration%>
                <%= form.hidden_field :first_time, value: false %>
                <%= form.hidden_field :plan_id, value: plans_selected.plan_id  %> 
                <%= form.hidden_field :day_used, value: 0 %>
                <%= form.hidden_field :activated, value: !plans_selected.activated %>

              <div>
                <%= form.submit "#{ plans_selected.activated ? "Desativate": "Activate" }", class:"btn btn-info" %>
              </div>

            <% end %>
          </td>
          <% end %>
      <% end %>


</div>
 

app/views/plans_selecteds/edit.html.erb
<h4 class="text-center text-pink">Editing plans selected</h4>


<%= render "form", plans_selected: @plans_selected %>

app/views/plans_selecteds/index.html.erb
<div class="container">

  <h4 class="text-center text-pink">Plans selecteds</h4>

  <% if current_user.profile.super_adminstrador? %>
  <div class="text-end">
    <%= link_to "Create new", new_plans_selected_path, class: "link-primary" %>
  </div>
  <% end %>
  <table class="table text-primary-emphasis">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Entrepreneur/Company</th>
        <th scope="col">User</th>
        <th scope="col">Plan Selected</th>
        <th scope="col">Duration</th>
        <th scope="col">Price(kz)</th>
        <th scope="col">Day used</th>
        <th scope="col">Activated</th>
        <th scope="col">First time</th>
      </tr>
    </thead>
    <tbody>
    <div id="plans_selecteds">
      <% @plans_selecteds.each do |plans_selected| %>
      <tr>
        <%= render plans_selected %>
      </tr>
      <% end %>
    </div>
  
    </tbody>
  </table>

<div>

app/views/plans_selecteds/new.html.erb
<h4 class="text-center text-pink">New plans selected</h4>

<%= render "form", plans_selected: @plans_selected %>

app/views/plans_selecteds/show.html.erb
<h4 class="text-pink text-center">Show</h4>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Entrepreneur/Company</th>
      <th scope="col">User</th>
      <th scope="col">Plan Selected</th>
      <th scope="col">Duration</th>
      <th scope="col">Price(kz)</th>
      <th scope="col">Day used</th>
      <th scope="col">Activated</th>
      <th scope="col">First time</th>
      <th scope="col">Ação</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <div id="plans_selecteds">
     <tr>
      <%= render @plans_selected %>
     </tr>
  </div>
 
  </tbody>
</table>