config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :contacts, only: [:create, :show]
  resources :plans_selecteds
  resources :plans
  
  mount Resque::Server.new, :at => "/resque"

  resources :favorite_lands, only: [:index, :create, :destroy]
  resources :favorite_houses, only: [:index, :create, :destroy]
  resources :profile_lands, only: [:index]
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :lands do 
    get 'show_images'
   
    collection do 
      get 'search'
    end
  end
  
  resources :houses do
    get 'show_images' 
    
    collection do
      get 'search'
      get 'search_advanced'
      get 'rent'
      get 'buy'
    end
  
  end

  root "home#index"

end

app/models/plan.rb
class Plan < ApplicationRecord
    has_rich_text :description
    has_many :plans_selected
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index ]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_plan

  # GET /plans or /plans.json
  def index
    @plans = Plan.all
    @plans_selected = PlansSelected.new
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url(locale: I18n.locale), notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def invalid_plan
      logger.error "Attemped to access invalid Plan #{params[:id]}"
      redirect_to plans_url(locale: I18n.locale), info: "Invalid Plan."
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:name_plans, :price, :description, :activated, :first_time)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
 <div class="container col-lg-6 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
        <%= bootstrap_form_with(model: plan) do |form| %>
          <% if plan.errors.any? %>
            <div style="color: red">
              <h5><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h5>

              <ul>
                <% plan.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

            <%= form.text_field :name_plans, class: 'text-light-emphasis' %>
            <%= form.number_field :price, class: 'text-light-emphasis' %>
            <%= form.rich_text_area :description, size: "70x5", class: 'text-light-emphasis' %>

          <div class="mb-3 d-grid gap-2">
            <%= form.submit class: "btn btn-info" %>
          </div>

          <%= link_to "Back to plans", plans_path %>
        <% end %>
    </div>
  </div>
</div>

app/views/plans/_plan.html.erb
  <div class="col" id="<%= dom_id plan %>">
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
        <h4 class="my-0 fw-normal text-center"><%= plan.name_plans %></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title text-center text-pink"><%= plan.price %><small class="text-muted fw-light">/mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4 text-primary-emphasis">
          <li><%= plan.description %></li>
          <br>
         
        </ul>
        <div>

          <%= bootstrap_form_with(model: @plans_selected) do |form| %>
          <% if @plans_selected.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(@plans_selected.errors.count, "error") %> prohibited this plans_selected from being saved:</h2>

              <ul>
                <% @plans_selected.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <% if user_signed_in? %>
            <% if current_user.profile.super_adminstrador? %>
              <%= link_to "Show this plan", plan , class:"w-100 btn btn-lg btn-pink mb-2"%>
            <% else %>
              <%= form.select :duration, PlansSelected.durations.keys %>
              <%= form.hidden_field :plan_id, value: plan.id %> 
              
              <div class="mb-3 d-grid gap-2">
                <%= form.submit class:"btn btn-info" %>
              </div>
            <% end %>
            
           <% end %>

         <% end %>

        <% if !user_signed_in?%>
          <%= link_to "Subscribe", new_plans_selected_path,  class:"w-100 btn btn-lg btn-pink mb-2"%>
        <% end %>
        </div>
     
      </div>
    </div>
  </div>


  

app/views/plans/edit.html.erb
<h4 class="text-center text-pink"> Editing plan</h4>
<%= render "form", plan: @plan %>

app/views/plans/index.html.erb
<div class="container py-3" >
  <h4 class="text-center text-pink"> Plans </h4>
    <div class="row row-cols-1 row-cols-md-3 mb-3"  id="plans">
        <% @plans.each do |plan| %>
          <%= render plan %>
        <% end %>
    </div>
</div>

app/views/plans/new.html.erb
<h4 class="text-center text-pink">New Plan</h4>


<%= render "form", plan: @plan %>

app/views/plans/show.html.erb
<div class="container py-3" >
  <div class="col" id="plans">
    <div class=" text-end">
      <%= link_to "New plan", new_plan_path, class:"link-primary"%>
    </div>    
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
        <h4 class="my-0 fw-normal text-center"><%= @plan.name_plans %></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title text-center text-pink"><%= @plan.price %><small class="text-muted fw-light">/mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4 text-primary-emphasis">
          <li><%= @plan.description %></li>
          <br>
         
        </ul>
        <div>
          <%= link_to "Edit this plan", edit_plan_path(@plan) , class:"w-100 btn btn-lg btn-outline-primary mb-2"%>
          <%= button_to "Destroy this plan", @plan, method: :delete, 
            data: { confirm: "Está ação irá eliminar este plano selecionado. Deseja continuar?", 
             turbo_confirm: "Está ação irá eliminar este plano selecionado. Deseja continuar?" }, 
             class: "w-100 btn btn-lg btn-outline-danger" %>
       </div>
     
      </div>
    </div>
  </div>
</div>

   